### ISSUE TITLE
Enable Travis CI support

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zc.zodbdgc#2]
When I created PR #1, I didn't see a Travis CI build kick off. (Unless I missed it, in which case I apologize.) Would it be possible to enable that for this repository? I don't have access and/or don't know how.

**Comment by mgedmin** [comment]
Should be fixed now.

**Comment by mgedmin** [comment]
Thank you for letting us know!

**Comment by mgedmin** [comment]
Welp, the build fails on Travis, and I don't understand why :(

**Comment by jamadden** [comment]
The Python 2.6 builds fail because of a change in the way `persistent.TimeStamp.TimeStamp` does its `repr`. There was some discussion about this in, e.g., [zopefoundation/persistent#12] (https://github.com/zopefoundation/persistent/issues/12). 

The Python 2.7 builds fail because `Unpickler.noload` is entirely broken under 2.7 (hence the point of PR #1, which incidentally fixes the tests under Python 2.6 as well).
