### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zc.zodbdgc#3]
Would it be possible to get a release to PyPI made including the new support for PyPy and Python 3 (#1)? I'm happy to do all of the work necessary if @jimfulton doesn't have the time and doesn't mind granting my PyPI account (jamadden) access.

Things I suspect need done for release:

- Since there is major new platform support, probably a version of 0.7.0 is more appropriate than 0.6.3
- We'll have the same wheel issue that @mgedmin ran into with zopefoundation/zodb#36 so it might be nice to fix that.

**Comment by jimfulton** [comment]
On Tue, Aug 25, 2015 at 5:02 PM, Jason Madden <notifications@github.com>
wrote:

> Would it be possible to get a release to PyPI made including the new
> support for PyPy and Python 3 (#1
> <https://github.com/zopefoundation/zc.zodbdgc/pull/1>)? I'm happy to do
> all of the work necessary if @jimfulton <https://github.com/jimfulton>
> doesn't have the time and doesn't mind granting my PyPI account (jamadden)
> access.
>

Done. You're an owner.


> Things I suspect need done for release:
>
>    - Since there is major new platform support, probably a version of
>    0.7.0 is more appropriate than 0.6.3
>
>
Or perhaps 1.0?



>
>    - We'll have the same wheel issue that @mgedmin
>    <https://github.com/mgedmin> ran into with zopefoundation/ZODB#36
>    <https://github.com/zopefoundation/ZODB/issues/36> so it might be nice
>    to fix that.
>
> Sigh.  Feel free to do what's simplest.

Especially for zodbdgc, I've been thinking of *not* using the old cPickle
noload mechanism but just doing the equivalent in Python.  I wish I had
time to work on this stuff.

Much thanks!

Jim

-- 
Jim Fulton
http://www.linkedin.com/in/jimfulton

**Comment by jamadden** [comment]
>>    - We'll have the same wheel issue that @mgedmin
>>    <https://github.com/mgedmin> ran into with zopefoundation/ZODB#36
>>    <https://github.com/zopefoundation/ZODB/issues/36> so it might be nice
>>    to fix that.

>  Sigh.  Feel free to do what's simplest.

The simplest thing would be to make the zodbpickle dependency non-optional and use it even under Python 2.6. Would you be okay with that? (Then that would definitely call for a version bump to 1.0 it seems to me.)

> Especially for zodbdgc, I've been thinking of *not* using the old cPickle
> noload mechanism but just doing the equivalent in Python.  I wish I had
> time to work on this stuff.

I wrote a Python implementation of noload in [zodbpickle](https://github.com/zopefoundation/zodbpickle/commit/4bd8b8c58a6ea4b4bbada092556fd668a22f3826) :) I suppose it could be copied here if you want, but that amount of code duplication makes my head hurt. Plus we'd lose the C speedups.

**Comment by jimfulton** [comment]
On Tue, Aug 25, 2015 at 6:57 PM, Jason Madden <notifications@github.com>
wrote:

>
>    - We'll have the same wheel issue that @mgedmin
>    <https://github.com/mgedmin> https://github.com/mgedmin ran into with
>    zopefoundation/ZODB#36
>    <https://github.com/zopefoundation/ZODB/issues/36>
>    zopefoundation/ZODB#36
>    <https://github.com/zopefoundation/ZODB/issues/36> so it might be nice
>    to fix that.
>
> Sigh. Feel free to do what's simplest.
>
> The simplest thing would be to make the zodbpickle dependency non-optional
> and use it even under Python 2.6. Would you be okay with that? (Then that
> would definitely call for a version bump to 1.0 it seems to me.)
>
Assuming that having zc.zodbdgc depend on zodbpickle doesn't change it's
behavior,
I'm fine with adding the dependency.

Jim

-- 
Jim Fulton
http://www.linkedin.com/in/jimfulton

**Comment by jamadden** [comment]
>> The simplest thing would be to make the zodbpickle dependency non-optional
>> and use it even under Python 2.6. Would you be okay with that? (Then that
>>  would definitely call for a version bump to 1.0 it seems to me.)
> Assuming that having zc.zodbdgc depend on zodbpickle doesn't change it's
> behavior, I'm fine with adding the dependency.

AFAICS, it won't :)

Regarding the version number, if we're going to do a 1.0, potentially signifying "backwards incompatibilities", I'd *really* like to get the PyPy/Python3 ``ResourceWarnings`` discussed [starting here](https://github.com/zopefoundation/zc.zodbdgc/pull/1#issuecomment-93383758) fixed. In short, they come from the undocumented, untested behaviour of ``gc_command`` returning a ``Bad`` object with an open temporary file. I had come up with a few options:

1. Document the features of `Bad`, including calling `close`. Add test cases for this and update the existing cases to properly close the object. This is more work, but has the advantage of not breaking any callers.

2. Make the on-disk behaviour of `Bad` optional, defaulting to an in-memory version only. This has the advantage of not requiring test changes or additions (to get the same level of coverage as current), plus it makes the GC process potentially faster by not requiring I/O. The disadvantage, aside from the implementation work, is that those (few?) callers that use the undocumented on-disk features will require a change.

3. Remove the undocumented on-disk features of `Bad`. Solves the leaks, improves test coverage, and GC speed. Breaks callers relying on them.

I like option 3 because Less Code, but that's where the potential breakage comes in. Option 2 might be a nice compromise. 

I'm happy to implement any of these options, or any other option you'd like.

Alternately, we could defer the issue and still call this release 0.7.0

**Comment by jamadden** [comment]
A variation on option 1 I thought of, and the one I think I would prefer if we need to keep the option to return an open ``Bad`` intact is to introduce a new API that does that, and make the existing APIs wrappers around it, except they close the object (and return ``None``). Existing callers that don't need the ``Bad`` object are unaffected. Existing callers that *do* need the object are broken and have to change their code---but they (possibly) need to change their code anyway to explicitly call ``close``.

**Comment by jamadden** [comment]
Another option that's a partial fix, suitable for 0.7.0: Using a ``tempfile.SpooledTemporaryFile`` with a suitably large ``max_size`` serves to both eliminate the ResourceWarnings from the tests and many common scenarios while also keeping the ability to limit maximum memory usage. 

This requires changing the serialization format from ``marshal`` to ``pickle`` because Python 2's ``marshal.dump`` can't write to a ``StringIO``. The good news is that this produces slightly smaller data; it does seem to be a tiny bit slower (55ms vs 67ms for dumping and 119ms vs 140ms for loading a very large refs list).

**Comment by jimfulton** [comment]
On Wed, Aug 26, 2015 at 8:21 AM, Jason Madden <notifications@github.com>
wrote:

> The simplest thing would be to make the zodbpickle dependency non-optional
> and use it even under Python 2.6. Would you be okay with that? (Then that
> would definitely call for a version bump to 1.0 it seems to me.)
> Assuming that having zc.zodbdgc depend on zodbpickle doesn't change it's
> behavior, I'm fine with adding the dependency.
>
> AFAICS, it won't :)
>
> Regarding the version number, if we're going to do a 1.0, potentially
> signifying "backwards incompatibilities",
>

In my mind, while 1.0 may signify backward compatibility, it usually
signifies emergence from experimental mode.



> I'd *really* like to get the PyPy/Python3 ResourceWarnings discussed starting
> here
> <https://github.com/zopefoundation/zc.zodbdgc/pull/1#issuecomment-93383758>
> fixed.
>
+1

> In short, they come from the undocumented, untested behaviour of
> gc_command returning a Bad object with an open temporary file.
>

This is purely in service of tests and generally pretty annoying otherwise.
:)

This tends to make the gc command painful cron jobs.


> I had come up with a few options:
>
>    1.
>
>    Document the features of Bad, including calling close. Add test cases
>    for this and update the existing cases to properly close the object. This
>    is more work, but has the advantage of not breaking any callers.
>    2.
>
>    Make the on-disk behaviour of Bad optional, defaulting to an in-memory
>    version only. This has the advantage of not requiring test changes or
>    additions (to get the same level of coverage as current), plus it makes the
>    GC process potentially faster by not requiring I/O. The disadvantage, aside
>    from the implementation work, is that those (few?) callers that use the
>    undocumented on-disk features will require a change.
>    3.
>
>    Remove the undocumented on-disk features of Bad. Solves the leaks,
>    improves test coverage, and GC speed. Breaks callers relying on them.
>
> I like option 3 because Less Code, but that's where the potential breakage
> comes in. Option 2 might be a nice compromise.
>
> I'm happy to implement any of these options, or any other option you'd
> like.
>

I suggest the following:

- add a ``test`` keyword option to gc_command. If provided, return bad.
  Otherwise, close bad and return None.

- Add a ``close`` option to ``Bad.iterator`` which closes the file at the
end of iteration. Pass
  this in tests.

I definitely want to keep the disk feature of Bad, as it's needed for large
databases.

Jim

-- 
Jim Fulton
http://www.linkedin.com/in/jimfulton

**Comment by jamadden** [comment]
>> Regarding the version number, if we're going to do a 1.0, potentially
>> signifying "backwards incompatibilities",
> In my mind, while 1.0 may signify backward compatibility, it usually
> signifies emergence from experimental mode.

Absolutely, I can agree 1.0 is extra special in that way: major digit change---possible incompatibilities/major changes from the semantic-versioning standpoint; magic number "1"---stable by convention. So if we have any major changes or stabilization to do before 1.0 would be the time :)

> I suggest the following:
[snip details about the ``test`` keyword argument]

Ok, thanks. That's *pretty* similar to the last suggestion (presented in a separate comment), in that it introduces separate APIs for users of ``Bad`` and leaves everyone else unaffected.

If it's agreed that the only reason ``Bad`` is being exposed is for testing purposes, then I would probably want to do something that makes that keyword argument return what the tests actually want: everywhere that they look at the results of ``gc_command``, they all do the same awkward dance: ``sorted(gc_command(...).iterator())``, so that could be simplified.

> I definitely want to keep the disk feature of Bad, as it's needed for large
> databases.

That was the strawman argument :) I definitely understand why the file may sometimes be needed.

I did some testing with a ``SpooledTemporaryFile``, and a 10MB in-memory buffer can hold ~2million references, scaling more or less linearly and with basically no code complication (https://github.com/zopefoundation/zc.zodbdgc/compare/spooled-temp-file). It seems like keeping the data in memory is probably a win, where possible, given the random seeks involved. But the key word is *seems*. That sort of thing is notoriously dependent on system configuration and load. Probably not worth it.

**Comment by jimfulton** [comment]
On Fri, Aug 28, 2015 at 8:10 AM, Jason Madden <notifications@github.com>
wrote:

> Regarding the version number, if we're going to do a 1.0, potentially
> signifying "backwards incompatibilities",
> In my mind, while 1.0 may signify backward compatibility, it usually
> signifies emergence from experimental mode.
>
> Absolutely, I can agree 1.0 is extra special in that way: major digit
> change---possible incompatibilities/major changes from the
> semantic-versioning standpoint; magic number "1"---stable by convention. So
> if we have any major changes or stabilization to do before 1.0 would be the
> time :)
>
> I suggest the following:
> [snip details about the test keyword argument]
>
> Ok, thanks. That's *pretty* similar to the last suggestion (presented in
> a separate comment), in that it introduces separate APIs for users of Bad
> and leaves everyone else unaffected.
>
> If it's agreed that the only reason Bad is being exposed is for testing
> purposes, then I would probably want to do something that makes that
> keyword argument return what the tests actually want: everywhere that they
> look at the results of gc_command, they all do the same awkward dance:
> sorted(gc_command(...).iterator()), so that could be simplified.
>
Good point. The current way this is done is a result of iteration. +1 to
making this simpler.



> I definitely want to keep the disk feature of Bad, as it's needed for large
> databases.
>
> That was the strawman argument :) I definitely understand why the file may
> sometimes be needed.
>
> I did some testing with a SpooledTemporaryFile, and a 10MB in-memory
> buffer can hold ~2million references, scaling more or less linearly and
> with basically no code complication (
> https://github.com/zopefoundation/zc.zodbdgc/compare/spooled-temp-file).
> It seems like keeping the data in memory is probably a win, where possible,
> given the random seeks involved. But the key word is *seems*. That sort
> of thing is notoriously dependent on system configuration and load.
> Probably not worth it.
>
<shrug> Even on disk, the data is often in memory thanks to the disk
cache.  I'm open to other implementations. The key is being able to be able
to handle large databases without
running out of memory.  When I wrote this, this was an issue for ZC.

Jim
